spring:
  mail:
    # 配置发邮平台，若为qq，则163换qq
    host: smtp.163.com
    username: xxxxxxxxxxxx@163.com  # 发邮件邮箱
    password: XXXXXXXXXXXX  # 非登录密码，为邮箱设置里的协议密码
    # 推荐配置
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

#    spring.mail.properties.mail.smtp.auth=true
#    spring.mail.properties.mail.smtp.starttls.enable=true
#    spring.mail.properties.mail.smtp.starttls.required=true
#
#    # SSL Config
#    spring.mail.port=465
#    spring.mail.protocol=smtp
#    spring.mail.default-encoding=UTF-8
#    spring.mail.properties.mail.smtp.ssl.enable=true
#    spring.mail.properties.mail.smtp.socketFactory.port=465
#    spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory